### ISSUE TITLE
figures/tables manuscript cleanup

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/McGregor_climate-sensitivity-variation#48]
# Figures & Tables

General:
- [x] update everything with change from 1994-66 to 1966.
- [x] deal with issue of .png tables getting labeled as figures (and consequent incorrect numbering of figures). Related to this, 
- [x] Becky figured out how to pretty easily make a similar to Table 1, 2, etc in R markdown. May be worth doing here.
- [ ] figure out how to put variable symbols into tables

Fig. droughts-
- [x] add density plot as second panel
- [x] color code drought shading to match density plot
- [x] remove shading from 1964-1965 (shading is for pre-drought period; these years are drought)
- [x] extend x-axis back to 1950

Fig. height-
 - [x] remove 'height' label from panels b-d
- [x] remove panel d? - see issue #57 
- [x] adjust NEON instrument heights slightly -- see [.pdf from John Schnebelen](https://github.com/SCBI-ForestGEO/McGregor_climate-sensitivity-variation/blob/master/data/heights/NEON/SCBI_TowerAsbuilt.pdf).
- [x] see issue #58 

Table 1-
- [x] fill in
- [x] note that it is currently placed incorrectly in the manuscript (in line, cut off)
- [x] minor cleanup and standardization (e.g., consistency with punctuation and capitalization in predictions)
- [ ] check table: errors may have been introduced with new results (see issue #60)
- [ ] when possible, write out variable names so that table makes sense stand-alone (and to avoid symbol formatting problems!)

Table 2-
- [x] doesn't fit, so move number of stems in each canopy position to SI (or format in Excel?)
- [x] code in R markdown
- [x] fix up formatting
- [ ] @mcgregorian1 , update numbers
- [x] add missing definitions, units, etc.
- [ ] put symbols in italics 
- [ ] remember that we'll need to fix TLP at proof stage

Table 3-
- [ ] replace values under range_DBH with "min-max" 
- [ ] add n cores analyzed
- [ ] replace codes with species names
- [ ] list in descending order of productivity 
- [ ] give ANPP_stem for each species
- [x]  move units from legend to table
- [ ] add SD on trait values
- [ ] formatting

Table 4- individual predictor tests 
- [x] remove variable name from coefficients columns, make extra rows for categorical variables (if this doesn't make sense, I can do it).
- [x] code in R markdown
- [ ] see if we can put dAIC>2 in bold
- [ ] did we use Y in the null models after it came out non-significant? (I think either way is justifiable, but make sure table is correct)

Table 5- best full models
- [x] format in Excel (issue #40)
- [x] code in R markdown
- [x] fix markup surrounding table. It was fine until I added a full legend...

# manuscript

General- 
- [x] left align text
- [ ] ensure consistent ,clean names/abbreviations to each variable. For ln-transformed variables, put e.g., "ln[*H*]"
- [ ] review and cite more papers (see #56 )
- [ ] integrate references
- [ ] review [New Phyt instructions for authors](https://nph-onlinelibrary-wiley-com.smithsonian.idm.oclc.org/hub/journal/14698137/about/author-guidelines), identify & work on needed changes.
- [ ] 1.5 line spacing
- [ ] word count: I added table on title page, as required by NP, and did rough assessment. We're currently about on track, but don't want to make it any more wordy.

Abstract-
- [ ] work on abstract (mainly @teixeirak )

Methods-
- [x] work on *Analysis* section
- [x] add methods for NEON vertical profiles

Results-
- [x] Fill in missing info in the section "*Focal droughts and their characteristics*"

Discussion-
- [x] adjust outline (Ian, I'm now thinking we should make some modifications to the version we discussed)
- [x] write first draft 

# supplementary info 

General-
- [ ] break out SI as a separate document. Ultimately, provided that it gets accepted at New Phyt, we'll want it in the [New Phyt SI template](https://github.com/SCBI-ForestGEO/McGregor_climate-sensitivity-variation/blob/master/manuscript/McGregor_SI_New_Phytologist_template.docx), although that's probably not necessary for the first submission. 
- [x] create bark thickness allometry table
- [ ] do a careful assessment of what needs to be in SI, add anything needed
- [ ] spell check! (pasting into word revealed how badly I type when there's no auto-correct/ spell check!)

 table S1-
- [x] replace `x` with `ln[DBH]`
- [x] Table S1 currently says the equation for FAGR as 1*x. It should be 0*x, and it looks like its that way in your code (line 804 [here](https://github.com/SCBI-ForestGEO/McGregor_climate-sensitivity-variation/blob/7fe44b4ba3b8a50805efd1e987a8ea7f4149b86c/scripts/canopy_position_analysis.R)). Please confirm/ change in the SI.

table S2 -
- [ ] would be more intuitive if you put a column for each drought scenario, with an "x" in columns where it comes out in the top. Otherwise the variables make sense

table S3- 
- [ ] clean up formatting (e.g., remove "NA"s)
- [ ] maybe add stats from pointer year analysis?

table S4-

table S5-
- [x] add traits/ height table 

Fig. map-
- [x] add species legend
