### ISSUE TITLE
Final tasks remaining

### ISSUE THREAD

**Issue by mcgregorian1** [SCBI-ForestGEO/McGregor_climate-sensitivity-variation#97]
This may not need to be an issue but I'm putting the remaining things that need to do be done (before submitting again) here so it's easier for me to remember.

I've put these in relative order of importance.

### statistics
- [X] fully compare Arima (ratio) with Rt and decide which is better. #92
  - we have decided the original Rt should be used. We can ignore all data that says arima
- [x] Redo the "reform" method from #95 for Rt (now that 92 is solved)
- [x] Figure out how to present the best (top) models. @teixeirak #94 
- [x] Look at top models with only traits that have consistent coefficients across droughts (#95)
  - [x] Run the full workflow for arimaratio and Rt using only PLA/TLP and save output tables.

### reviewers
- [x] Go through and address comments by Reviewer 1
  - [x] Figure out remaining questions
- [x] Address comments by Reviewer 2
  - [x] Figure out remaining questions
- [x] Address comments by Reviewer 3
  - [x] Figure out remaining questions
- [x] Address comments by Reviewer 4
  - [x] Figure out remaining questions

### Other formatting
- [x] Add citation #91
- [x] Make sure all figure (#87) labels are correct
- [x] Make sure table numbers are correct 
  - [x] Decide what other SI tables we want to have past S3 (e.g. do we want to include the variance inflation factor (VIF)? or the residual deviations difference between arimaratio and Rt?)
- [x] Fix table headings and SI clean-up #88, #89
